//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPR.DataHelper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPR.DataHelper.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;Month&quot;: &quot;201810&quot;,
        ///&quot;Week&quot;: &quot;Week 1&quot;,
        ///&quot;Sum of Impression&quot;: &quot;48441&quot;,
        ///&quot;Click Through&quot;: &quot;0.000495448070849074&quot;,
        ///&quot;Sum of Offered&quot;: &quot;24&quot;,
        ///&quot;Conv(HandledToOffered)&quot;: &quot;1&quot;,
        ///&quot;Sum of Handled&quot;: &quot;24&quot;,
        ///&quot;Sum of TotalLeads_TQL&quot;: &quot;12&quot;,
        ///&quot;Sum of NonSalesProspect&quot;: &quot;3&quot;,
        ///&quot;Conv(LeadsToNon-SalesProspect)&quot;: &quot;0.25&quot;,
        ///&quot;Sum of SalesProspect&quot;: &quot;9&quot;,
        ///&quot;Conv(LeadsToSalesLeads)&quot;: &quot;0.75&quot;,
        ///&quot;Sum of Kickbacks&quot;: &quot;0&quot;,
        ///&quot;Sum of TotalTQL&quot;: &quot;5&quot;,
        ///&quot;Sum of IsTQLAccepted&quot;: &quot;1&quot;,
        ///&quot;Sum of IsTQLRejected&quot;: &quot;0&quot;,
        ///&quot;Sum of RecipientDisqualifiedT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JProperites {
            get {
                return ResourceManager.GetString("JProperites", resourceCulture);
            }
        }
    }
}
